"""Constants for Heishamon by Lutarym integration."""

DOMAIN = "heishamon_lutarym"

CONF_HOST = "host"
CONF_USERNAME = "username"
CONF_PASSWORD = "password"
CONF_UPDATE_INTERVAL = "update_interval"
CONF_LISTENING_ONLY = "listening_only"

DEFAULT_UPDATE_INTERVAL = 30
DEFAULT_LISTENING_ONLY = True

# Alle 143 Topics mit vollständiger Konfiguration
HEISHAMON_TOPICS = {
    "TOP0": {"name": "Heatpump_State", "type": "sensor", "unit": None, "icon": "mdi:power", "device_class": None},
    "TOP1": {"name": "Pump_Flow", "type": "sensor", "unit": "l/min", "icon": "mdi:water", "device_class": None},
    "TOP2": {"name": "Force_DHW_State", "type": "sensor", "unit": None, "icon": "mdi:water-boiler", "device_class": None},
    "TOP3": {"name": "Quiet_Mode_Schedule", "type": "sensor", "unit": None, "icon": "mdi:volume-mute", "device_class": None},
    "TOP4": {"name": "Operating_Mode_State", "type": "sensor", "unit": None, "icon": "mdi:cog", "device_class": None},
    "TOP5": {"name": "Main_Inlet_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": "temperature"},
    "TOP6": {"name": "Main_Outlet_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": "temperature"},
    "TOP7": {"name": "Main_Target_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": "temperature"},
    "TOP8": {"name": "Compressor_Freq", "type": "sensor", "unit": "Hz", "icon": "mdi:sine-wave", "device_class": None},
    "TOP9": {"name": "DHW_Target_Temp", "type": "number", "unit": "°C", "icon": "mdi:thermometer", "device_class": "temperature", "min": 40, "max": 75},
    "TOP10": {"name": "DHW_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": "temperature"},
    "TOP11": {"name": "Operations_Hours", "type": "sensor", "unit": "h", "icon": "mdi:clock", "device_class": None},
    "TOP12": {"name": "Operations_Counter", "type": "sensor", "unit": None, "icon": "mdi:counter", "device_class": None},
    "TOP13": {"name": "Main_Schedule_State", "type": "sensor", "unit": None, "icon": "mdi:calendar", "device_class": None},
    "TOP14": {"name": "Outside_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": "temperature"},
    "TOP15": {"name": "Heat_Power_Production", "type": "sensor", "unit": "W", "icon": "mdi:flash", "device_class": "power"},
    "TOP16": {"name": "Heat_Power_Consumption", "type": "sensor", "unit": "W", "icon": "mdi:flash", "device_class": "power"},
    "TOP17": {"name": "Powerful_Mode_Time", "type": "sensor", "unit": "min", "icon": "mdi:timer", "device_class": None},
    "TOP18": {"name": "Quiet_Mode_Level", "type": "sensor", "unit": None, "icon": "mdi:volume-mute", "device_class": None},
    "TOP19": {"name": "Holiday_Mode_State", "type": "sensor", "unit": None, "icon": "mdi:beach", "device_class": None},
    "TOP20": {"name": "ThreeWay_Valve_State", "type": "sensor", "unit": None, "icon": "mdi:valve", "device_class": None},
    "TOP21": {"name": "Outside_Pipe_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": "temperature"},
    "TOP22": {"name": "DHW_Heat_Delta", "type": "sensor", "unit": "K", "icon": "mdi:delta", "device_class": None},
    "TOP23": {"name": "Heat_Delta", "type": "sensor", "unit": "K", "icon": "mdi:delta", "device_class": None},
    "TOP24": {"name": "Cool_Delta", "type": "sensor", "unit": "K", "icon": "mdi:delta", "device_class": None},
    "TOP25": {"name": "DHW_Holiday_Shift_Temp", "type": "number", "unit": "°C", "icon": "mdi:thermometer", "device_class": None, "min": -15, "max": 15},
    "TOP26": {"name": "Defrosting_State", "type": "sensor", "unit": None, "icon": "mdi:snowflake", "device_class": None},
    "TOP27": {"name": "Z1_Heat_Request_Temp", "type": "number", "unit": "°C", "icon": "mdi:thermometer", "device_class": None, "min": -5, "max": 50},
    "TOP28": {"name": "Z1_Cool_Request_Temp", "type": "number", "unit": "°C", "icon": "mdi:thermometer", "device_class": None, "min": 5, "max": 20},
    "TOP29": {"name": "Z1_Heat_Curve_Target_High_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": None},
    "TOP30": {"name": "Z1_Heat_Curve_Target_Low_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": None},
    "TOP31": {"name": "Z1_Heat_Curve_Outside_High_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": None},
    "TOP32": {"name": "Z1_Heat_Curve_Outside_Low_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": None},
    "TOP33": {"name": "Room_Thermostat_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": "temperature"},
    "TOP34": {"name": "Z2_Heat_Request_Temp", "type": "number", "unit": "°C", "icon": "mdi:thermometer", "device_class": None, "min": -5, "max": 50},
    "TOP35": {"name": "Z2_Cool_Request_Temp", "type": "number", "unit": "°C", "icon": "mdi:thermometer", "device_class": None, "min": 5, "max": 20},
    "TOP36": {"name": "Z1_Water_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": "temperature"},
    "TOP37": {"name": "Z2_Water_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": "temperature"},
    "TOP38": {"name": "Cool_Power_Production", "type": "sensor", "unit": "W", "icon": "mdi:flash", "device_class": "power"},
    "TOP39": {"name": "Cool_Power_Consumption", "type": "sensor", "unit": "W", "icon": "mdi:flash", "device_class": "power"},
    "TOP40": {"name": "DHW_Power_Production", "type": "sensor", "unit": "W", "icon": "mdi:flash", "device_class": "power"},
    "TOP41": {"name": "DHW_Power_Consumption", "type": "sensor", "unit": "W", "icon": "mdi:flash", "device_class": "power"},
    "TOP42": {"name": "Z1_Water_Target_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": "temperature"},
    "TOP43": {"name": "Z2_Water_Target_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": "temperature"},
    "TOP44": {"name": "Error", "type": "sensor", "unit": None, "icon": "mdi:alert", "device_class": None},
    "TOP45": {"name": "Room_Holiday_Shift_Temp", "type": "number", "unit": "°C", "icon": "mdi:thermometer", "device_class": None, "min": -15, "max": 15},
    "TOP46": {"name": "Buffer_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": "temperature"},
    "TOP47": {"name": "Solar_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": "temperature"},
    "TOP48": {"name": "Pool_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": "temperature"},
    "TOP49": {"name": "Main_Hex_Outlet_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": "temperature"},
    "TOP50": {"name": "Discharge_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": "temperature"},
    "TOP51": {"name": "Inside_Pipe_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": "temperature"},
    "TOP52": {"name": "Defrost_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": "temperature"},
    "TOP53": {"name": "Eva_Outlet_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": "temperature"},
    "TOP54": {"name": "Bypass_Outlet_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": "temperature"},
    "TOP55": {"name": "Ipm_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": "temperature"},
    "TOP56": {"name": "Z1_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": "temperature"},
    "TOP57": {"name": "Z2_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": "temperature"},
    "TOP58": {"name": "DHW_Heater_State", "type": "sensor", "unit": None, "icon": "mdi:water-boiler", "device_class": None},
    "TOP59": {"name": "Room_Heater_State", "type": "sensor", "unit": None, "icon": "mdi:radiator", "device_class": None},
    "TOP60": {"name": "Internal_Heater_State", "type": "sensor", "unit": None, "icon": "mdi:radiator", "device_class": None},
    "TOP61": {"name": "External_Heater_State", "type": "sensor", "unit": None, "icon": "mdi:radiator", "device_class": None},
    "TOP62": {"name": "Fan1_Motor_Speed", "type": "sensor", "unit": "U/min", "icon": "mdi:fan", "device_class": None},
    "TOP63": {"name": "Fan2_Motor_Speed", "type": "sensor", "unit": "U/min", "icon": "mdi:fan", "device_class": None},
    "TOP64": {"name": "High_Pressure", "type": "sensor", "unit": "kgf/cm²", "icon": "mdi:gauge", "device_class": None},
    "TOP65": {"name": "Pump_Speed", "type": "sensor", "unit": "U/min", "icon": "mdi:pump", "device_class": None},
    "TOP66": {"name": "Low_Pressure", "type": "sensor", "unit": "kgf/cm²", "icon": "mdi:gauge", "device_class": None},
    "TOP67": {"name": "Compressor_Current", "type": "sensor", "unit": "A", "icon": "mdi:flash", "device_class": "current"},
    "TOP68": {"name": "Force_Heater_State", "type": "sensor", "unit": None, "icon": "mdi:radiator", "device_class": None},
    "TOP69": {"name": "Sterilization_State", "type": "sensor", "unit": None, "icon": "mdi:water-boiler", "device_class": None},
    "TOP70": {"name": "Sterilization_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": "temperature"},
    "TOP71": {"name": "Sterilization_Max_Time", "type": "sensor", "unit": "min", "icon": "mdi:timer", "device_class": None},
    "TOP72": {"name": "Z1_Cool_Curve_Target_High_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": None},
    "TOP73": {"name": "Z1_Cool_Curve_Target_Low_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": None},
    "TOP74": {"name": "Z1_Cool_Curve_Outside_High_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": None},
    "TOP75": {"name": "Z1_Cool_Curve_Outside_Low_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": None},
    "TOP76": {"name": "Heating_Mode", "type": "sensor", "unit": None, "icon": "mdi:thermometer", "device_class": None},
    "TOP77": {"name": "Heating_Off_Outdoor_Temp", "type": "number", "unit": "°C", "icon": "mdi:thermometer", "device_class": None, "min": 5, "max": 35},
    "TOP78": {"name": "Heater_On_Outdoor_Temp", "type": "number", "unit": "°C", "icon": "mdi:thermometer", "device_class": None, "min": -15, "max": 20},
    "TOP79": {"name": "Heat_To_Cool_Temp", "type": "number", "unit": "°C", "icon": "mdi:thermometer", "device_class": None, "min": -20, "max": 35},
    "TOP80": {"name": "Cool_To_Heat_Temp", "type": "number", "unit": "°C", "icon": "mdi:thermometer", "device_class": None, "min": -20, "max": 35},
    "TOP81": {"name": "Cooling_Mode", "type": "sensor", "unit": None, "icon": "mdi:thermometer", "device_class": None},
    "TOP82": {"name": "Z2_Heat_Curve_Target_High_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": None},
    "TOP83": {"name": "Z2_Heat_Curve_Target_Low_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": None},
    "TOP84": {"name": "Z2_Heat_Curve_Outside_High_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": None},
    "TOP85": {"name": "Z2_Heat_Curve_Outside_Low_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": None},
    "TOP86": {"name": "Z2_Cool_Curve_Target_High_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": None},
    "TOP87": {"name": "Z2_Cool_Curve_Target_Low_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": None},
    "TOP88": {"name": "Z2_Cool_Curve_Outside_High_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": None},
    "TOP89": {"name": "Z2_Cool_Curve_Outside_Low_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": None},
    "TOP90": {"name": "Room_Heater_Operations_Hours", "type": "sensor", "unit": "h", "icon": "mdi:clock", "device_class": None},
    "TOP91": {"name": "DHW_Heater_Operations_Hours", "type": "sensor", "unit": "h", "icon": "mdi:clock", "device_class": None},
    "TOP92": {"name": "Heat_Pump_Model", "type": "sensor", "unit": None, "icon": "mdi:information", "device_class": None},
    "TOP93": {"name": "Pump_Duty", "type": "sensor", "unit": "%", "icon": "mdi:percent", "device_class": None},
    "TOP94": {"name": "Zones_State", "type": "sensor", "unit": None, "icon": "mdi:cog", "device_class": None},
    "TOP95": {"name": "Max_Pump_Duty", "type": "sensor", "unit": "%", "icon": "mdi:percent", "device_class": None},
    "TOP96": {"name": "Heater_Delay_Time", "type": "sensor", "unit": "min", "icon": "mdi:timer", "device_class": None},
    "TOP97": {"name": "Heater_Start_Delta", "type": "sensor", "unit": "K", "icon": "mdi:delta", "device_class": None},
    "TOP98": {"name": "Heater_Stop_Delta", "type": "sensor", "unit": "K", "icon": "mdi:delta", "device_class": None},
    "TOP99": {"name": "Buffer_Installed", "type": "sensor", "unit": None, "icon": "mdi:database", "device_class": None},
    "TOP100": {"name": "DHW_Installed", "type": "sensor", "unit": None, "icon": "mdi:database", "device_class": None},
    "TOP101": {"name": "Solar_Mode", "type": "sensor", "unit": None, "icon": "mdi:solar-panel", "device_class": None},
    "TOP102": {"name": "Solar_On_Delta", "type": "sensor", "unit": "K", "icon": "mdi:delta", "device_class": None},
    "TOP103": {"name": "Solar_Off_Delta", "type": "sensor", "unit": "K", "icon": "mdi:delta", "device_class": None},
    "TOP104": {"name": "Solar_Frost_Protection", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": None},
    "TOP105": {"name": "Solar_High_Limit", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": None},
    "TOP106": {"name": "Pump_Flowrate_Mode", "type": "sensor", "unit": None, "icon": "mdi:cog", "device_class": None},
    "TOP107": {"name": "Liquid_Type", "type": "sensor", "unit": None, "icon": "mdi:water", "device_class": None},
    "TOP108": {"name": "Alt_External_Sensor", "type": "sensor", "unit": None, "icon": "mdi:thermometer", "device_class": None},
    "TOP109": {"name": "Anti_Freeze_Mode", "type": "sensor", "unit": None, "icon": "mdi:snowflake", "device_class": None},
    "TOP110": {"name": "Optional_PCB", "type": "sensor", "unit": None, "icon": "mdi:circuit-board", "device_class": None},
    "TOP111": {"name": "Z2_Sensor_Settings", "type": "sensor", "unit": None, "icon": "mdi:cog", "device_class": None},
    "TOP112": {"name": "Z1_Sensor_Settings", "type": "sensor", "unit": None, "icon": "mdi:cog", "device_class": None},
    "TOP113": {"name": "Buffer_Tank_Delta", "type": "sensor", "unit": "K", "icon": "mdi:delta", "device_class": None},
    "TOP114": {"name": "External_Pad_Heater", "type": "sensor", "unit": None, "icon": "mdi:radiator", "device_class": None},
    "TOP115": {"name": "Water_Pressure", "type": "sensor", "unit": "bar", "icon": "mdi:gauge", "device_class": None},
    "TOP116": {"name": "Second_Inlet_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": "temperature"},
    "TOP117": {"name": "Economizer_Outlet_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": "temperature"},
    "TOP118": {"name": "Second_Room_Thermostat_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": "temperature"},
    "TOP119": {"name": "External_Control", "type": "sensor", "unit": None, "icon": "mdi:remote", "device_class": None},
    "TOP120": {"name": "External_Heat_Cool_Control", "type": "sensor", "unit": None, "icon": "mdi:remote", "device_class": None},
    "TOP121": {"name": "External_Error_Signal", "type": "sensor", "unit": None, "icon": "mdi:alert", "device_class": None},
    "TOP122": {"name": "External_Compressor_Control", "type": "sensor", "unit": None, "icon": "mdi:remote", "device_class": None},
    "TOP123": {"name": "Z1_Pump_State", "type": "sensor", "unit": None, "icon": "mdi:pump", "device_class": None},
    "TOP124": {"name": "Z2_Pump_State", "type": "sensor", "unit": None, "icon": "mdi:pump", "device_class": None},
    "TOP125": {"name": "TwoWay_Valve_State", "type": "sensor", "unit": None, "icon": "mdi:valve", "device_class": None},
    "TOP126": {"name": "ThreeWay_Valve_State2", "type": "sensor", "unit": None, "icon": "mdi:valve", "device_class": None},
    "TOP127": {"name": "Z1_Valve_PID", "type": "sensor", "unit": None, "icon": "mdi:valve", "device_class": None},
    "TOP128": {"name": "Z2_Valve_PID", "type": "sensor", "unit": None, "icon": "mdi:valve", "device_class": None},
    "TOP129": {"name": "Bivalent_Control", "type": "sensor", "unit": None, "icon": "mdi:cog", "device_class": None},
    "TOP130": {"name": "Bivalent_Mode", "type": "sensor", "unit": None, "icon": "mdi:cog", "device_class": None},
    "TOP131": {"name": "Bivalent_Start_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": None},
    "TOP132": {"name": "Bivalent_Advanced_Heat", "type": "sensor", "unit": None, "icon": "mdi:cog", "device_class": None},
    "TOP133": {"name": "Bivalent_Advanced_DHW", "type": "sensor", "unit": None, "icon": "mdi:cog", "device_class": None},
    "TOP134": {"name": "Bivalent_Advanced_Start_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": None},
    "TOP135": {"name": "Bivalent_Advanced_Stop_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": None},
    "TOP136": {"name": "Bivalent_Advanced_Start_Delay", "type": "sensor", "unit": "min", "icon": "mdi:timer", "device_class": None},
    "TOP137": {"name": "Bivalent_Advanced_Stop_Delay", "type": "sensor", "unit": "min", "icon": "mdi:timer", "device_class": None},
    "TOP138": {"name": "Bivalent_Advanced_DHW_Delay", "type": "sensor", "unit": "min", "icon": "mdi:timer", "device_class": None},
    "TOP139": {"name": "Heating_Control", "type": "sensor", "unit": None, "icon": "mdi:cog", "device_class": None},
    "TOP140": {"name": "Smart_DHW", "type": "sensor", "unit": None, "icon": "mdi:cog", "device_class": None},
    "TOP141": {"name": "Quiet_Mode_Priority", "type": "sensor", "unit": None, "icon": "mdi:volume-mute", "device_class": None},
    "TOP142": {"name": "Expansion_Valve", "type": "sensor", "unit": "steps", "icon": "mdi:valve", "device_class": None},
    "TOP143": {"name": "DHW_Sensor_Selection", "type": "sensor", "unit": None, "icon": "mdi:cog", "device_class": None},
}

# SET Commands für Steuerung
SET_COMMANDS = {
    "SetHeatpump": {"type": "switch", "icon": "mdi:power"},
    "SetHolidayMode": {"type": "switch", "icon": "mdi:beach"},
    "SetQuietMode": {"type": "select", "icon": "mdi:volume-mute", "options": ["Off", "Less Power", "Even Less Power", "Least Power"]},
    "SetPowerfulMode": {"type": "select", "icon": "mdi:flash", "options": ["Off", "30 min", "60 min", "90 min"]},
    "SetZ1HeatRequestTemperature": {"type": "number", "icon": "mdi:thermometer", "min": -5, "max": 50, "unit": "°C"},
    "SetZ1CoolRequestTemperature": {"type": "number", "icon": "mdi:thermometer", "min": 5, "max": 20, "unit": "°C"},
    "SetZ2HeatRequestTemperature": {"type": "number", "icon": "mdi:thermometer", "min": -5, "max": 50, "unit": "°C"},
    "SetZ2CoolRequestTemperature": {"type": "number", "icon": "mdi:thermometer", "min": 5, "max": 20, "unit": "°C"},
    "SetOperationMode": {"type": "select", "icon": "mdi:cog", "options": ["Heat only", "Cool only", "Auto", "DHW only", "Heat+DHW", "Cool+DHW", "Auto+DHW", "Auto(Cool)", "Auto(Cool)+DHW"]},
    "SetForceDHW": {"type": "switch", "icon": "mdi:water-boiler"},
    "SetDHWTemp": {"type": "number", "icon": "mdi:thermometer", "min": 40, "max": 75, "unit": "°C"},
    "SetForceDefrost": {"type": "switch", "icon": "mdi:snowflake"},
    "SetForceSterilization": {"type": "switch", "icon": "mdi:water-boiler"},
    "SetPump": {"type": "switch", "icon": "mdi:pump"},
    "SetMainSchedule": {"type": "switch", "icon": "mdi:calendar"},
    "SetAltExternalSensor": {"type": "switch", "icon": "mdi:thermometer"},
    "SetBuffer": {"type": "switch", "icon": "mdi:database"},
    "SetHeatingOffOutdoorTemp": {"type": "number", "icon": "mdi:thermometer", "min": 5, "max": 35, "unit": "°C"},
    "SetHeaterOnOutdoorTemp": {"type": "number", "icon": "mdi:thermometer", "min": -15, "max": 20, "unit": "°C"},
    "SetExternalControl": {"type": "switch", "icon": "mdi:remote"},
    "SetExternalError": {"type": "switch", "icon": "mdi:alert"},
    "SetExternalCompressorControl": {"type": "switch", "icon": "mdi:remote"},
    "SetBivalentControl": {"type": "switch", "icon": "mdi:cog"},
    "SetForceHeater": {"type": "switch", "icon": "mdi:radiator"},
    "SetReset": {"type": "switch", "icon": "mdi:restart"},
    "SetDHWHeaterState": {"type": "switch", "icon": "mdi:water-boiler"},
    "SetRoomHeaterState": {"type": "switch", "icon": "mdi:radiator"},
}
