"""Constants for Heishamon by Lutarym."""

DOMAIN = "heishamon_lutarym"

CONF_HOST = "host"
CONF_USERNAME = "username"
CONF_PASSWORD = "password"
CONF_UPDATE_INTERVAL = "update_interval"
CONF_LISTENING_ONLY = "listening_only"

# Standardtakt. HeishaMon fragt die Waermepumpe selbst etwa alle fuenf
# Sekunden ab, schneller liefert sie keine neuen Werte.
DEFAULT_UPDATE_INTERVAL = 5
MIN_UPDATE_INTERVAL = 1
MAX_UPDATE_INTERVAL = 300
DEFAULT_LISTENING_ONLY = True

# Topic-Namen 1:1 aus HeishaMon decode.h (Firmware-Quellcode).
# "numeric": False bei den beiden Textwerten TOP44 (Error) und TOP92 (Heat_Pump_Model).
HEISHAMON_TOPICS = {
    "TOP0": {"name": "Heatpump_State", "type": "sensor", "unit": None, "icon": "mdi:power", "device_class": None, "numeric": True},
    "TOP1": {"name": "Pump_Flow", "type": "sensor", "unit": "l/min", "icon": "mdi:water", "device_class": None, "numeric": True},
    "TOP2": {"name": "Force_DHW_State", "type": "sensor", "unit": None, "icon": "mdi:water-boiler", "device_class": None, "numeric": True},
    "TOP3": {"name": "Quiet_Mode_Schedule", "type": "sensor", "unit": None, "icon": "mdi:volume-mute", "device_class": None, "numeric": True},
    "TOP4": {"name": "Operating_Mode_State", "type": "sensor", "unit": None, "icon": "mdi:cog", "device_class": None, "numeric": True},
    "TOP5": {"name": "Main_Inlet_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": "temperature", "numeric": True},
    "TOP6": {"name": "Main_Outlet_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": "temperature", "numeric": True},
    "TOP7": {"name": "Main_Target_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": "temperature", "numeric": True},
    "TOP8": {"name": "Compressor_Freq", "type": "sensor", "unit": "Hz", "icon": "mdi:sine-wave", "device_class": None, "numeric": True},
    "TOP9": {"name": "DHW_Target_Temp", "type": "number", "unit": "°C", "icon": "mdi:thermometer", "device_class": "temperature", "numeric": True, "set_command": "SetDHWTemp", "min": 40, "max": 75},
    "TOP10": {"name": "DHW_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": "temperature", "numeric": True},
    "TOP11": {"name": "Operations_Hours", "type": "sensor", "unit": "h", "icon": "mdi:clock", "device_class": None, "numeric": True},
    "TOP12": {"name": "Operations_Counter", "type": "sensor", "unit": None, "icon": "mdi:counter", "device_class": None, "numeric": True},
    "TOP13": {"name": "Main_Schedule_State", "type": "sensor", "unit": None, "icon": "mdi:calendar", "device_class": None, "numeric": True},
    "TOP14": {"name": "Outside_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": "temperature", "numeric": True},
    "TOP15": {"name": "Heat_Power_Production", "type": "sensor", "unit": "W", "icon": "mdi:flash", "device_class": "power", "numeric": True},
    "TOP16": {"name": "Heat_Power_Consumption", "type": "sensor", "unit": "W", "icon": "mdi:flash", "device_class": "power", "numeric": True},
    "TOP17": {"name": "Powerful_Mode_Time", "type": "sensor", "unit": "min", "icon": "mdi:timer", "device_class": None, "numeric": True},
    "TOP18": {"name": "Quiet_Mode_Level", "type": "sensor", "unit": None, "icon": "mdi:volume-mute", "device_class": None, "numeric": True},
    "TOP19": {"name": "Holiday_Mode_State", "type": "sensor", "unit": None, "icon": "mdi:beach", "device_class": None, "numeric": True},
    "TOP20": {"name": "ThreeWay_Valve_State", "type": "sensor", "unit": None, "icon": "mdi:valve", "device_class": None, "numeric": True},
    "TOP21": {"name": "Outside_Pipe_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": "temperature", "numeric": True},
    "TOP22": {"name": "DHW_Heat_Delta", "type": "sensor", "unit": "K", "icon": "mdi:delta", "device_class": None, "numeric": True},
    "TOP23": {"name": "Heat_Delta", "type": "sensor", "unit": "K", "icon": "mdi:delta", "device_class": None, "numeric": True},
    "TOP24": {"name": "Cool_Delta", "type": "sensor", "unit": "K", "icon": "mdi:delta", "device_class": None, "numeric": True},
    "TOP25": {"name": "DHW_Holiday_Shift_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": None, "numeric": True},
    "TOP26": {"name": "Defrosting_State", "type": "sensor", "unit": None, "icon": "mdi:snowflake", "device_class": None, "numeric": True},
    "TOP27": {"name": "Z1_Heat_Request_Temp", "type": "number", "unit": "°C", "icon": "mdi:thermometer", "device_class": None, "numeric": True, "set_command": "SetZ1HeatRequestTemperature", "min": -5, "max": 50},
    "TOP28": {"name": "Z1_Cool_Request_Temp", "type": "number", "unit": "°C", "icon": "mdi:thermometer", "device_class": None, "numeric": True, "set_command": "SetZ1CoolRequestTemperature", "min": -5, "max": 20},
    "TOP29": {"name": "Z1_Heat_Curve_Target_High_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": None, "numeric": True},
    "TOP30": {"name": "Z1_Heat_Curve_Target_Low_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": None, "numeric": True},
    "TOP31": {"name": "Z1_Heat_Curve_Outside_High_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": None, "numeric": True},
    "TOP32": {"name": "Z1_Heat_Curve_Outside_Low_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": None, "numeric": True},
    "TOP33": {"name": "Room_Thermostat_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": "temperature", "numeric": True},
    "TOP34": {"name": "Z2_Heat_Request_Temp", "type": "number", "unit": "°C", "icon": "mdi:thermometer", "device_class": None, "numeric": True, "set_command": "SetZ2HeatRequestTemperature", "min": -5, "max": 50},
    "TOP35": {"name": "Z2_Cool_Request_Temp", "type": "number", "unit": "°C", "icon": "mdi:thermometer", "device_class": None, "numeric": True, "set_command": "SetZ2CoolRequestTemperature", "min": -5, "max": 20},
    "TOP36": {"name": "Z1_Water_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": "temperature", "numeric": True},
    "TOP37": {"name": "Z2_Water_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": "temperature", "numeric": True},
    "TOP38": {"name": "Cool_Power_Production", "type": "sensor", "unit": "W", "icon": "mdi:flash", "device_class": "power", "numeric": True},
    "TOP39": {"name": "Cool_Power_Consumption", "type": "sensor", "unit": "W", "icon": "mdi:flash", "device_class": "power", "numeric": True},
    "TOP40": {"name": "DHW_Power_Production", "type": "sensor", "unit": "W", "icon": "mdi:flash", "device_class": "power", "numeric": True},
    "TOP41": {"name": "DHW_Power_Consumption", "type": "sensor", "unit": "W", "icon": "mdi:flash", "device_class": "power", "numeric": True},
    "TOP42": {"name": "Z1_Water_Target_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": "temperature", "numeric": True},
    "TOP43": {"name": "Z2_Water_Target_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": "temperature", "numeric": True},
    "TOP44": {"name": "Error", "type": "sensor", "unit": None, "icon": "mdi:alert", "device_class": None, "numeric": False},
    "TOP45": {"name": "Room_Holiday_Shift_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": None, "numeric": True},
    "TOP46": {"name": "Buffer_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": "temperature", "numeric": True},
    "TOP47": {"name": "Solar_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": "temperature", "numeric": True},
    "TOP48": {"name": "Pool_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": "temperature", "numeric": True},
    "TOP49": {"name": "Main_Hex_Outlet_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": "temperature", "numeric": True},
    "TOP50": {"name": "Discharge_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": "temperature", "numeric": True},
    "TOP51": {"name": "Inside_Pipe_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": "temperature", "numeric": True},
    "TOP52": {"name": "Defrost_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": "temperature", "numeric": True},
    "TOP53": {"name": "Eva_Outlet_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": "temperature", "numeric": True},
    "TOP54": {"name": "Bypass_Outlet_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": "temperature", "numeric": True},
    "TOP55": {"name": "Ipm_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": "temperature", "numeric": True},
    "TOP56": {"name": "Z1_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": "temperature", "numeric": True},
    "TOP57": {"name": "Z2_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": "temperature", "numeric": True},
    "TOP58": {"name": "DHW_Heater_State", "type": "sensor", "unit": None, "icon": "mdi:water-boiler", "device_class": None, "numeric": True},
    "TOP59": {"name": "Room_Heater_State", "type": "sensor", "unit": None, "icon": "mdi:radiator", "device_class": None, "numeric": True},
    "TOP60": {"name": "Internal_Heater_State", "type": "sensor", "unit": None, "icon": "mdi:radiator", "device_class": None, "numeric": True},
    "TOP61": {"name": "External_Heater_State", "type": "sensor", "unit": None, "icon": "mdi:radiator", "device_class": None, "numeric": True},
    "TOP62": {"name": "Fan1_Motor_Speed", "type": "sensor", "unit": "U/min", "icon": "mdi:fan", "device_class": None, "numeric": True},
    "TOP63": {"name": "Fan2_Motor_Speed", "type": "sensor", "unit": "U/min", "icon": "mdi:fan", "device_class": None, "numeric": True},
    "TOP64": {"name": "High_Pressure", "type": "sensor", "unit": "kgf/cm²", "icon": "mdi:gauge", "device_class": None, "numeric": True},
    "TOP65": {"name": "Pump_Speed", "type": "sensor", "unit": "U/min", "icon": "mdi:pump", "device_class": None, "numeric": True},
    "TOP66": {"name": "Low_Pressure", "type": "sensor", "unit": "kgf/cm²", "icon": "mdi:gauge", "device_class": None, "numeric": True},
    "TOP67": {"name": "Compressor_Current", "type": "sensor", "unit": "A", "icon": "mdi:flash", "device_class": "current", "numeric": True},
    "TOP68": {"name": "Force_Heater_State", "type": "sensor", "unit": None, "icon": "mdi:radiator", "device_class": None, "numeric": True},
    "TOP69": {"name": "Sterilization_State", "type": "sensor", "unit": None, "icon": "mdi:water-boiler", "device_class": None, "numeric": True},
    "TOP70": {"name": "Sterilization_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": "temperature", "numeric": True},
    "TOP71": {"name": "Sterilization_Max_Time", "type": "sensor", "unit": "min", "icon": "mdi:timer", "device_class": None, "numeric": True},
    "TOP72": {"name": "Z1_Cool_Curve_Target_High_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": None, "numeric": True},
    "TOP73": {"name": "Z1_Cool_Curve_Target_Low_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": None, "numeric": True},
    "TOP74": {"name": "Z1_Cool_Curve_Outside_High_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": None, "numeric": True},
    "TOP75": {"name": "Z1_Cool_Curve_Outside_Low_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": None, "numeric": True},
    "TOP76": {"name": "Heating_Mode", "type": "sensor", "unit": None, "icon": "mdi:thermometer", "device_class": None, "numeric": True},
    "TOP77": {"name": "Heating_Off_Outdoor_Temp", "type": "number", "unit": "°C", "icon": "mdi:thermometer", "device_class": None, "numeric": True, "set_command": "SetHeatingOffOutdoorTemp", "min": 5, "max": 35},
    "TOP78": {"name": "Heater_On_Outdoor_Temp", "type": "number", "unit": "°C", "icon": "mdi:thermometer", "device_class": None, "numeric": True, "set_command": "SetHeaterOnOutdoorTemp", "min": -15, "max": 20},
    "TOP79": {"name": "Heat_To_Cool_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": None, "numeric": True},
    "TOP80": {"name": "Cool_To_Heat_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": None, "numeric": True},
    "TOP81": {"name": "Cooling_Mode", "type": "sensor", "unit": None, "icon": "mdi:thermometer", "device_class": None, "numeric": True},
    "TOP82": {"name": "Z2_Heat_Curve_Target_High_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": None, "numeric": True},
    "TOP83": {"name": "Z2_Heat_Curve_Target_Low_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": None, "numeric": True},
    "TOP84": {"name": "Z2_Heat_Curve_Outside_High_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": None, "numeric": True},
    "TOP85": {"name": "Z2_Heat_Curve_Outside_Low_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": None, "numeric": True},
    "TOP86": {"name": "Z2_Cool_Curve_Target_High_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": None, "numeric": True},
    "TOP87": {"name": "Z2_Cool_Curve_Target_Low_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": None, "numeric": True},
    "TOP88": {"name": "Z2_Cool_Curve_Outside_High_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": None, "numeric": True},
    "TOP89": {"name": "Z2_Cool_Curve_Outside_Low_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": None, "numeric": True},
    "TOP90": {"name": "Room_Heater_Operations_Hours", "type": "sensor", "unit": "h", "icon": "mdi:clock", "device_class": None, "numeric": True},
    "TOP91": {"name": "DHW_Heater_Operations_Hours", "type": "sensor", "unit": "h", "icon": "mdi:clock", "device_class": None, "numeric": True},
    "TOP92": {"name": "Heat_Pump_Model", "type": "sensor", "unit": None, "icon": "mdi:information", "device_class": None, "numeric": False},
    "TOP93": {"name": "Pump_Duty", "type": "sensor", "unit": "%", "icon": "mdi:percent", "device_class": None, "numeric": True},
    "TOP94": {"name": "Zones_State", "type": "sensor", "unit": None, "icon": "mdi:cog", "device_class": None, "numeric": True},
    "TOP95": {"name": "Max_Pump_Duty", "type": "sensor", "unit": "%", "icon": "mdi:percent", "device_class": None, "numeric": True},
    "TOP96": {"name": "Heater_Delay_Time", "type": "sensor", "unit": "min", "icon": "mdi:timer", "device_class": None, "numeric": True},
    "TOP97": {"name": "Heater_Start_Delta", "type": "sensor", "unit": "K", "icon": "mdi:delta", "device_class": None, "numeric": True},
    "TOP98": {"name": "Heater_Stop_Delta", "type": "sensor", "unit": "K", "icon": "mdi:delta", "device_class": None, "numeric": True},
    "TOP99": {"name": "Buffer_Installed", "type": "sensor", "unit": None, "icon": "mdi:database", "device_class": None, "numeric": True},
    "TOP100": {"name": "DHW_Installed", "type": "sensor", "unit": None, "icon": "mdi:database", "device_class": None, "numeric": True},
    "TOP101": {"name": "Solar_Mode", "type": "sensor", "unit": None, "icon": "mdi:solar-panel", "device_class": None, "numeric": True},
    "TOP102": {"name": "Solar_On_Delta", "type": "sensor", "unit": "K", "icon": "mdi:delta", "device_class": None, "numeric": True},
    "TOP103": {"name": "Solar_Off_Delta", "type": "sensor", "unit": "K", "icon": "mdi:delta", "device_class": None, "numeric": True},
    "TOP104": {"name": "Solar_Frost_Protection", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": None, "numeric": True},
    "TOP105": {"name": "Solar_High_Limit", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": None, "numeric": True},
    "TOP106": {"name": "Pump_Flowrate_Mode", "type": "sensor", "unit": None, "icon": "mdi:cog", "device_class": None, "numeric": True},
    "TOP107": {"name": "Liquid_Type", "type": "sensor", "unit": None, "icon": "mdi:water", "device_class": None, "numeric": True},
    "TOP108": {"name": "Alt_External_Sensor", "type": "sensor", "unit": None, "icon": "mdi:thermometer", "device_class": None, "numeric": True},
    "TOP109": {"name": "Anti_Freeze_Mode", "type": "sensor", "unit": None, "icon": "mdi:snowflake", "device_class": None, "numeric": True},
    "TOP110": {"name": "Optional_PCB", "type": "sensor", "unit": None, "icon": "mdi:circuit-board", "device_class": None, "numeric": True},
    "TOP111": {"name": "Z1_Sensor_Settings", "type": "sensor", "unit": None, "icon": "mdi:cog", "device_class": None, "numeric": True},
    "TOP112": {"name": "Z2_Sensor_Settings", "type": "sensor", "unit": None, "icon": "mdi:cog", "device_class": None, "numeric": True},
    "TOP113": {"name": "Buffer_Tank_Delta", "type": "sensor", "unit": "K", "icon": "mdi:delta", "device_class": None, "numeric": True},
    "TOP114": {"name": "External_Pad_Heater", "type": "sensor", "unit": None, "icon": "mdi:radiator", "device_class": None, "numeric": True},
    "TOP115": {"name": "Water_Pressure", "type": "sensor", "unit": "bar", "icon": "mdi:gauge", "device_class": None, "numeric": True},
    "TOP116": {"name": "Second_Inlet_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": "temperature", "numeric": True},
    "TOP117": {"name": "Economizer_Outlet_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": "temperature", "numeric": True},
    "TOP118": {"name": "Second_Room_Thermostat_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": "temperature", "numeric": True},
    "TOP119": {"name": "External_Control", "type": "sensor", "unit": None, "icon": "mdi:remote", "device_class": None, "numeric": True},
    "TOP120": {"name": "External_Heat_Cool_Control", "type": "sensor", "unit": None, "icon": "mdi:remote", "device_class": None, "numeric": True},
    "TOP121": {"name": "External_Error_Signal", "type": "sensor", "unit": None, "icon": "mdi:alert", "device_class": None, "numeric": True},
    "TOP122": {"name": "External_Compressor_Control", "type": "sensor", "unit": None, "icon": "mdi:remote", "device_class": None, "numeric": True},
    "TOP123": {"name": "Z2_Pump_State", "type": "sensor", "unit": None, "icon": "mdi:pump", "device_class": None, "numeric": True},
    "TOP124": {"name": "Z1_Pump_State", "type": "sensor", "unit": None, "icon": "mdi:pump", "device_class": None, "numeric": True},
    "TOP125": {"name": "TwoWay_Valve_State", "type": "sensor", "unit": None, "icon": "mdi:valve", "device_class": None, "numeric": True},
    "TOP126": {"name": "ThreeWay_Valve_State2", "type": "sensor", "unit": None, "icon": "mdi:valve", "device_class": None, "numeric": True},
    "TOP127": {"name": "Z1_Valve_PID", "type": "sensor", "unit": None, "icon": "mdi:valve", "device_class": None, "numeric": True},
    "TOP128": {"name": "Z2_Valve_PID", "type": "sensor", "unit": None, "icon": "mdi:valve", "device_class": None, "numeric": True},
    "TOP129": {"name": "Bivalent_Control", "type": "sensor", "unit": None, "icon": "mdi:cog", "device_class": None, "numeric": True},
    "TOP130": {"name": "Bivalent_Mode", "type": "sensor", "unit": None, "icon": "mdi:cog", "device_class": None, "numeric": True},
    "TOP131": {"name": "Bivalent_Start_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": None, "numeric": True},
    "TOP132": {"name": "Bivalent_Advanced_Heat", "type": "sensor", "unit": None, "icon": "mdi:cog", "device_class": None, "numeric": True},
    "TOP133": {"name": "Bivalent_Advanced_DHW", "type": "sensor", "unit": None, "icon": "mdi:cog", "device_class": None, "numeric": True},
    "TOP134": {"name": "Bivalent_Advanced_Start_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": None, "numeric": True},
    "TOP135": {"name": "Bivalent_Advanced_Stop_Temp", "type": "sensor", "unit": "°C", "icon": "mdi:thermometer", "device_class": None, "numeric": True},
    "TOP136": {"name": "Bivalent_Advanced_Start_Delay", "type": "sensor", "unit": "min", "icon": "mdi:timer", "device_class": None, "numeric": True},
    "TOP137": {"name": "Bivalent_Advanced_Stop_Delay", "type": "sensor", "unit": "min", "icon": "mdi:timer", "device_class": None, "numeric": True},
    "TOP138": {"name": "Bivalent_Advanced_DHW_Delay", "type": "sensor", "unit": "min", "icon": "mdi:timer", "device_class": None, "numeric": True},
    "TOP139": {"name": "Heating_Control", "type": "sensor", "unit": None, "icon": "mdi:cog", "device_class": None, "numeric": True},
    "TOP140": {"name": "Smart_DHW", "type": "sensor", "unit": None, "icon": "mdi:cog", "device_class": None, "numeric": True},
    "TOP141": {"name": "Quiet_Mode_Priority", "type": "sensor", "unit": None, "icon": "mdi:volume-mute", "device_class": None, "numeric": True},
    "TOP142": {"name": "Expansion_Valve", "type": "sensor", "unit": "steps", "icon": "mdi:valve", "device_class": None, "numeric": True},
    "TOP143": {"name": "DHW_Sensor_Selection", "type": "sensor", "unit": None, "icon": "mdi:cog", "device_class": None, "numeric": True},
}

# SET-Kommandos, verifiziert aus HeishaMon commands.h.
SWITCH_COMMANDS = {
    "SetHeatpump": {"icon": "mdi:power"},
    "SetPump": {"icon": "mdi:pump"},
    "SetForceDHW": {"icon": "mdi:water-boiler"},
    "SetForceDefrost": {"icon": "mdi:snowflake"},
    "SetForceSterilization": {"icon": "mdi:water-boiler"},
    "SetForceHeater": {"icon": "mdi:radiator"},
    "SetHolidayMode": {"icon": "mdi:beach"},
    "SetMainSchedule": {"icon": "mdi:calendar"},
    "SetAltExternalSensor": {"icon": "mdi:thermometer"},
    "SetBuffer": {"icon": "mdi:database"},
    "SetExternalControl": {"icon": "mdi:remote"},
    "SetExternalError": {"icon": "mdi:alert"},
    "SetExternalCompressorControl": {"icon": "mdi:remote"},
    "SetBivalentControl": {"icon": "mdi:cog"},
    "SetDHWHeaterState": {"icon": "mdi:water-boiler"},
    "SetRoomHeaterState": {"icon": "mdi:radiator"},
}

SELECT_COMMANDS = {
    "SetOperationMode": {
        "icon": "mdi:cog",
        "option_count": 7,
        "state_topic": "TOP4",
    },
    "SetQuietMode": {
        "icon": "mdi:volume-mute",
        "option_count": 4,
        "state_topic": "TOP18",
    },
    "SetPowerfulMode": {
        "icon": "mdi:flash",
        "option_count": 4,
        "state_topic": "TOP17",
    },
}
