"""Deutsche Bezeichnungen der HeishaMon-Topics."""

TOPIC_NAMES_DE = {
    "TOP0": "Waermepumpe Status", "TOP1": "Pumpen Durchfluss",
    "TOP2": "Warmwasser erzwingen", "TOP3": "Ruhemodus Zeitplan",
    "TOP4": "Betriebsmodus", "TOP5": "Ruecklauftemperatur",
    "TOP6": "Vorlauftemperatur", "TOP7": "Vorlauf Solltemperatur",
    "TOP8": "Verdichterfrequenz", "TOP9": "Warmwasser Solltemperatur",
    "TOP10": "Warmwasser Isttemperatur", "TOP11": "Betriebsstunden",
    "TOP12": "Startvorgaenge", "TOP13": "Zeitplan Status",
    "TOP14": "Aussentemperatur", "TOP15": "Heizleistung",
    "TOP16": "Heiz Stromaufnahme", "TOP17": "Powermodus Restzeit",
    "TOP18": "Ruhemodus Stufe", "TOP19": "Urlaubsmodus",
    "TOP20": "Dreiwegeventil", "TOP21": "Aussenrohr Temperatur",
    "TOP22": "Warmwasser Delta", "TOP23": "Heiz Delta",
    "TOP24": "Kuehl Delta", "TOP25": "Warmwasser Urlaubsversatz",
    "TOP26": "Abtauung", "TOP27": "Zone 1 Heiz Solltemperatur",
    "TOP28": "Zone 1 Kuehl Solltemperatur", "TOP29": "Zone 1 Heizkurve Ziel hoch",
    "TOP30": "Zone 1 Heizkurve Ziel tief", "TOP31": "Zone 1 Heizkurve Aussen hoch",
    "TOP32": "Zone 1 Heizkurve Aussen tief", "TOP33": "Raumthermostat Temperatur",
    "TOP34": "Zone 2 Heiz Solltemperatur", "TOP35": "Zone 2 Kuehl Solltemperatur",
    "TOP36": "Zone 1 Wassertemperatur", "TOP37": "Zone 2 Wassertemperatur",
    "TOP38": "Kuehlleistung", "TOP39": "Kuehl Stromaufnahme",
    "TOP40": "Warmwasser Leistung", "TOP41": "Warmwasser Stromaufnahme",
    "TOP42": "Zone 1 Wasser Solltemperatur", "TOP43": "Zone 2 Wasser Solltemperatur",
    "TOP44": "Fehlercode", "TOP45": "Raum Urlaubsversatz",
    "TOP46": "Puffertemperatur", "TOP47": "Solartemperatur",
    "TOP48": "Pooltemperatur", "TOP49": "Waermetauscher Austritt",
    "TOP50": "Heissgastemperatur", "TOP51": "Innenrohr Temperatur",
    "TOP52": "Abtautemperatur", "TOP53": "Verdampfer Austritt",
    "TOP54": "Bypass Austritt", "TOP55": "IPM Temperatur",
    "TOP56": "Zone 1 Raumtemperatur", "TOP57": "Zone 2 Raumtemperatur",
    "TOP58": "Warmwasser Heizstab", "TOP59": "Raum Heizstab",
    "TOP60": "Interner Heizstab", "TOP61": "Externer Heizstab",
    "TOP62": "Luefter 1 Drehzahl", "TOP63": "Luefter 2 Drehzahl",
    "TOP64": "Hochdruck", "TOP65": "Pumpendrehzahl",
    "TOP66": "Niederdruck", "TOP67": "Verdichterstrom",
    "TOP68": "Notheizung aktiv", "TOP69": "Sterilisation aktiv",
    "TOP70": "Sterilisation Temperatur", "TOP71": "Sterilisation Maximaldauer",
    "TOP72": "Zone 1 Kuehlkurve Ziel hoch", "TOP73": "Zone 1 Kuehlkurve Ziel tief",
    "TOP74": "Zone 1 Kuehlkurve Aussen hoch", "TOP75": "Zone 1 Kuehlkurve Aussen tief",
    "TOP76": "Heizmodus", "TOP77": "Heizgrenze Aussentemperatur",
    "TOP78": "Heizstab ab Aussentemperatur", "TOP79": "Umschaltung Heizen zu Kuehlen",
    "TOP80": "Umschaltung Kuehlen zu Heizen", "TOP81": "Kuehlmodus",
    "TOP82": "Zone 2 Heizkurve Ziel hoch", "TOP83": "Zone 2 Heizkurve Ziel tief",
    "TOP84": "Zone 2 Heizkurve Aussen hoch", "TOP85": "Zone 2 Heizkurve Aussen tief",
    "TOP86": "Zone 2 Kuehlkurve Ziel hoch", "TOP87": "Zone 2 Kuehlkurve Ziel tief",
    "TOP88": "Zone 2 Kuehlkurve Aussen hoch", "TOP89": "Zone 2 Kuehlkurve Aussen tief",
    "TOP90": "Raum Heizstab Betriebsstunden", "TOP91": "Warmwasser Heizstab Betriebsstunden",
    "TOP92": "Waermepumpen Modell", "TOP93": "Pumpenleistung",
    "TOP94": "Zonen Konfiguration", "TOP95": "Maximale Pumpenleistung",
    "TOP96": "Heizstab Verzoegerung", "TOP97": "Heizstab Start Delta",
    "TOP98": "Heizstab Stop Delta", "TOP99": "Pufferspeicher vorhanden",
    "TOP100": "Warmwasserspeicher vorhanden", "TOP101": "Solarmodus",
    "TOP102": "Solar Ein Delta", "TOP103": "Solar Aus Delta",
    "TOP104": "Solar Frostschutz", "TOP105": "Solar Maximaltemperatur",
    "TOP106": "Durchfluss Modus", "TOP107": "Fluessigkeitstyp",
    "TOP108": "Alternativer Aussenfuehler", "TOP109": "Frostschutzmodus",
    "TOP110": "Optionale Platine", "TOP111": "Zone 1 Fuehler Einstellung",
    "TOP112": "Zone 2 Fuehler Einstellung", "TOP113": "Puffer Delta",
    "TOP114": "Externe Bodenheizung", "TOP115": "Wasserdruck",
    "TOP116": "Zweiter Ruecklauffuehler", "TOP117": "Economizer Austritt",
    "TOP118": "Zweiter Raumthermostat", "TOP119": "Externe Steuerung",
    "TOP120": "Externe Heiz Kuehl Steuerung", "TOP121": "Externes Fehlersignal",
    "TOP122": "Externe Verdichtersteuerung", "TOP123": "Zone 2 Pumpe",
    "TOP124": "Zone 1 Pumpe", "TOP125": "Zweiwegeventil",
    "TOP126": "Dreiwegeventil 2", "TOP127": "Zone 1 Ventil PID",
    "TOP128": "Zone 2 Ventil PID", "TOP129": "Bivalenzsteuerung",
    "TOP130": "Bivalenzmodus", "TOP131": "Bivalenz Starttemperatur",
    "TOP132": "Bivalenz erweitert Heizen", "TOP133": "Bivalenz erweitert Warmwasser",
    "TOP134": "Bivalenz erweitert Starttemperatur", "TOP135": "Bivalenz erweitert Stoptemperatur",
    "TOP136": "Bivalenz erweitert Startverzoegerung", "TOP137": "Bivalenz erweitert Stopverzoegerung",
    "TOP138": "Bivalenz erweitert Warmwasserverzoegerung", "TOP139": "Heizungssteuerung",
    "TOP140": "Smart Warmwasser", "TOP141": "Ruhemodus Prioritaet",
    "TOP142": "Expansionsventil", "TOP143": "Warmwasserfuehler Auswahl",
}

COMMAND_NAMES_DE = {
    "SetHeatpump": "Waermepumpe", "SetPump": "Umwaelzpumpe",
    "SetForceDHW": "Warmwasser erzwingen", "SetForceDefrost": "Abtauung erzwingen",
    "SetForceSterilization": "Sterilisation erzwingen", "SetForceHeater": "Notheizung",
    "SetHolidayMode": "Urlaubsmodus", "SetMainSchedule": "Zeitplan",
    "SetAltExternalSensor": "Alternativer Aussenfuehler", "SetBuffer": "Pufferspeicher",
    "SetExternalControl": "Externe Steuerung", "SetExternalError": "Externes Fehlersignal",
    "SetExternalCompressorControl": "Externe Verdichtersteuerung",
    "SetBivalentControl": "Bivalenzsteuerung",
    "SetDHWHeaterState": "Warmwasser Heizstab", "SetRoomHeaterState": "Raum Heizstab",
    "SetOperationMode": "Betriebsmodus", "SetQuietMode": "Ruhemodus",
    "SetPowerfulMode": "Powermodus", "SetDHWTemp": "Warmwasser Solltemperatur",
    "SetZ1HeatRequestTemperature": "Zone 1 Heiz Sollwert",
    "SetZ1CoolRequestTemperature": "Zone 1 Kuehl Sollwert",
    "SetZ2HeatRequestTemperature": "Zone 2 Heiz Sollwert",
    "SetZ2CoolRequestTemperature": "Zone 2 Kuehl Sollwert",
    "SetHeatingOffOutdoorTemp": "Heizgrenze Aussentemperatur",
    "SetHeaterOnOutdoorTemp": "Heizstab ab Aussentemperatur",
}
